# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the React app
RUN npm run build

# Install a simple HTTP server for serving the build files
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Serve the build files
CMD ["serve", "-s", "build", "-l", "3000"]
