# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Copy the .env file from backend directory
COPY .env .env



# Expose the port the app runs on
EXPOSE 5000

# Start the application (fix the path issue)
CMD ["node", "server.js"]
